// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoOjMHfkybbv1z8IiW0OBcAQUfegbuWuU',
    appId: '1:974108948791:web:33a248bb07a087ac4282b2',
    messagingSenderId: '974108948791',
    projectId: 'trashtocash-project',
    authDomain: 'trashtocash-project.firebaseapp.com',
    storageBucket: 'trashtocash-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQtauv8m9T_7GdlzFka4IunLygrPko3Wo',
    appId: '1:974108948791:android:aafebfe779c848d34282b2',
    messagingSenderId: '974108948791',
    projectId: 'trashtocash-project',
    storageBucket: 'trashtocash-project.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoOjMHfkybbv1z8IiW0OBcAQUfegbuWuU',
    appId: '1:974108948791:web:dfcc4d496743c4274282b2',
    messagingSenderId: '974108948791',
    projectId: 'trashtocash-project',
    authDomain: 'trashtocash-project.firebaseapp.com',
    storageBucket: 'trashtocash-project.firebasestorage.app',
  );
}
